### ISSUE TITLE
Crashes server when using

### ISSUE THREAD

**Issue by MATTSUXXS** [SpyMan10/backpackmod-1.16-old#12]
I have a 1.19 fabric aternos server with this mod and whenever I tried opening the backpack it crashed my server

**Comment by SpyMan10** [comment]
Hello please add Crashlog from server side. I will fix as fast as possible

**Comment by shigzn** [comment]
This is the crash-report I got from the same issue.
[crash-2022-07-08_20.14.16-server.txt](https://github.com/SpyMan10/backpackmod/files/9077679/crash-2022-07-08_20.14.16-server.txt)

**Comment by SpyMan10** [comment]
I haven't crash where I try to open it. I already saw a similar problem but I don't known why that happen. Can you tell me what other mods you're using please

**Comment by shigzn** [comment]
![image](https://user-images.githubusercontent.com/108997182/178120412-d96feca1-2801-4740-8d6f-1d569b81943e.png)

**Comment by pepsitrip** [comment]
helo i get this bug too yes i relly lyke the mod pls fix

**Comment by pepsitrip** [comment]
> This is the crash-report I got from the same issue. [crash-2022-07-08_20.14.16-server.txt](https://github.com/SpyMan10/backpackmod/files/9077679/crash-2022-07-08_20.14.16-server.txt)

yes i atach cras log sory for bed engles im brasil

**Comment by itisFarzin** [comment]
i have same issue on 1.19

https://pastebin.com/u9Yhtxv5

**Comment by SpyMan10** [comment]
Done. fixed in version 4.0.1
https://www.curseforge.com/minecraft/mc-mods/backpackmod/files/all
