### ISSUE TITLE
So... where is the config?

### ISSUE THREAD

**Issue by Trogdayton** [SpyMan10/backpackmod-1.16-old#26]
I've re-downloaded, reloaded configs in game, checked and double and triple checked the folders. Still no config file, even though it says there is one in the readme. Am I just totally oblivious? I'm on the 1.18.2 version. Latest as of 7/26/22

**Comment by SpyMan10** [comment]
Check the game folder used with your minecraft instance and you should have a config folder into, the mod config file is created here.

the default minecraft instance is located at `~/appdata/roaming/.minecraft/` on Windows
If you're using a modpack check where the minecraft instance was created and you should have a config folder with `backpackmod.json`

**Comment by Trogdayton** [comment]
Is the folder named backpack mod? Because it doesn't seem to exist. If it's
a loose file in the config folder I also don't see it. I'm using a curse
forge modpack, and I'm in the config folder, but I got nothing. Is it just
for 1.19?

**Comment by SpyMan10** [comment]
Curseforge create another ".minecraft" directory, check your modpack settings on curseforge launcher, you will be able to open this directory with file explorer, and you will find a config folder.

**Comment by Trogdayton** [comment]
Yeah, that's the one I'm looking at. Doesn't seem to be there. I'm not at
home right now, but when I get back I'll screenshot.

**Comment by Trogdayton** [comment]
![image](https://user-images.githubusercontent.com/93630831/181367897-69917064-a53a-421f-b4f5-8fcc60589e65.png)
![image](https://user-images.githubusercontent.com/93630831/181367957-5c476611-417b-4ac1-8edc-e35b5ef76ebb.png)
![image](https://user-images.githubusercontent.com/93630831/181368063-bb2daa9f-91aa-43aa-a878-ea3e53b478f9.png)
I don't see it. Is it in a backpackmod folder? Or is it a loose file called backpackmod.json?

**Comment by SpyMan10** [comment]
Config directory should contains a file `backpackmod.json`

Check logs to ensure the file is correctly created or loaded during mod initialization at startup

**Comment by Trogdayton** [comment]
Thanks, I'll check it out.

**Comment by Trogdayton** [comment]
I'll go ahead and close this, but just FYI it never actually generated, not sure why.
