### ISSUE TITLE
Crashes on Apex Frabric 1.18.2 Server

### ISSUE THREAD

**Issue by htmoore** [SpyMan10/backpackmod-1.16-old#3]
You can craft the backpack just fine. The problem is when you try and open the backpack, it immediately crashes the server. Attached is the server crash report.

[crash-2022-04-18_23.44.27-server.txt](https://github.com/SpyMan10/backpackmod/files/8513170/crash-2022-04-18_23.44.27-server.txt)

**Comment by SpyMan10** [comment]
I tried to fix it in version 3.1.1, download it on http://curseforge.com , if there no changes, please provide me both logs from client and server, and the full mod list. I don't close this issue until the problem isn't totally fixed.

**Comment by htmoore** [comment]
It is working. Great job SpyMan10.

**Comment by SpyMan10** [comment]
Ok nice
