### ISSUE TITLE
Modpack update

### ISSUE THREAD

**Issue by gamerpotion** [SpyMan10/backpackmod-1.16-old#31]
Hey, sorry its not an issue but a request -  I am using your backpack mod in my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg
there is an official server that comes with the pack, 

we are moving to 1.19.2 and users are afraid of losing their items, so is there any chance you have looked into updating to 1.19.2 ?

**Comment by SpyMan10** [comment]
Version 1.19 still should work on 1.19.2 and item storage will not be affected by updating the mod.
Backpack content are saved using ItemStack NBT data, there no chance to lose it when updating this mod from 1.19.x to 1.19.2. If you not sure about that try yourself, and leave here a comment if you found something bad with this mod

**Comment by gamerpotion** [comment]
> Version 1.19 still should work on 1.19.2 and item storage will not be affected by updating the mod. Backpack content are saved using ItemStack NBT data, there no chance to lose it when updating this mod from 1.19.x to 1.19.2. If you not sure about that try yourself, and leave here a comment if you found something bad with this mod

great!  if its possible, could you please tick the checkbox on CurseForge for 1.19.2 (in files section) ?  then I can include it in the official modpack installation

**Comment by SpyMan10** [comment]
done.

https://www.curseforge.com/minecraft/mc-mods/backpackmod/files/3898767

**Comment by gamerpotion** [comment]
Many Thanks! :)
