### ISSUE TITLE
[Enhancement] Add ability to equip / unequip backpack into / from a hidden slot and access the backpack by certain key-bind

### ISSUE THREAD

**Issue by MadProbe** [SpyMan10/backpackmod-1.16-old#7]
This will provide increased usability to backpacks - the backpack won't consume slot in the toolbar or inventory and can be easily  and quickly accessed by a certain key-bind without need to drag the backpack into the toolbar and open it from there.
This feature exists in the Iron Backpacks mod which I believe was the spiritual successor to this mod.

**Comment by SpyMan10** [comment]
#2
