### ISSUE TITLE
[Enhancement] Add ability to configure the number of rows and columns of inventory of backpacks.

### ISSUE THREAD

**Issue by MadProbe** [SpyMan10/backpackmod-1.16-old#8]
Yet I think this option is somewhat unsafe because it can reduce the number of slots of all backpacks and make it so the items that does not fit in the backpack just go into the void.
Also I would like to have an option to configure the number of rows and slots without limits (or as much as possibly can be done with the current Minecraft and Fabric API)
And as I said in previous issue, this feature also exists in [the Iron Backpacks mod](https://github.com/gr8pefish/IronBackpacks) and you might find useful to look at the implementation of these features in this mod.

**Comment by SpyMan10** [comment]
This features is actually in dev on branch [1.18.2-custom-cfg](https://github.com/SpyMan10/backpackmod/tree/1.18.2-custom-cfg)

**Comment by MadProbe** [comment]
Sorry for creating issues without proper checks but thank you anyway!
